apiVersion: skaffold/v1beta8
kind: Config
profiles:
- name: local
  build:
    insecureRegistries: ["localhost:32000"]	
    artifacts:
    - image: localhost:32000/zipkin
    local:
      push: true
      useDockerCLI: true  
  deploy:
    kubectl:
      manifests:
      - config/local/*.yaml