apiVersion: v1
kind: Template
labels:
    template: "zipkin-1.30.3"
metadata:
  name: zipkin-template
  annotations:
    description: "Template to deploy Person grpc service"
objects:
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    labels:
      app: zipkin
    name: zipkin
    namespace: myproject
  spec:
    replicas: 1
    selector:
      app: zipkin
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          app: zipkin
      spec:
        containers:
          - image: '172.30.1.1:5000/myproject/zipkin:1.30.3'
            imagePullPolicy: IfNotPresent
            name: zipkin
        dnsPolicy: ClusterFirst
        restartPolicy: Always
    triggers:
      - type: ConfigChange

- kind: Service
  apiVersion: v1
  metadata:
    name: zipkin-service
    namespace: myproject
  spec:
      ports:
        - name: zipkin-collector-port
          protocol: TCP
          port: 9411
          targetPort: 9411
          nodePort: 30000
      selector:
        app: zipkin
      type: NodePort
      sessionAffinity: None

